### ISSUE TITLE
Faces-HQ dataset could not download properly

### ISSUE THREAD

**Issue by sysu17363040** [cc-hpc-itwm/DeepFakeDetection#1]
Hi, the Faces-HQ dataset on Google Drive has been reported could not download since I download it three times (the Internet is not stable enough) . Can I ask if there is another way to download the dataset? Thanks a lot and hope for your reply.

**Comment by keuperj** [comment]
Hello,
well, the files are on google drive - usually this works reliably (we had many downloads so far). If your problem still exists, we could split the large file into several parts ...
