### ISSUE TITLE
the parameter in SVM

### ISSUE THREAD

**Issue by MARD1NO** [cc-hpc-itwm/DeepFakeDetection#10]
I wonder know whether you have some suggestions about choose SVM parameters in different resolutions? I capture the video clip and covert to 1024x1024 .jpg.I use the parameter in FacesHQ,the accuracy is only about 45% in balanced dataset.

**Comment by RicardDurall** [comment]
I would recommend to look for the best hyper-paarmeters (check [here](https://scikit-learn.org/stable/auto_examples/model_selection/plot_grid_search_digits.html)) for your specific dataset, since they can vary between different datasets. Also it is recommendable to plot the 1D power spectrum to know how big or small the overlap between classes is.

**Comment by MARD1NO** [comment]
> I would recommend to look for the best hyper-paarmeters (check [here](https://scikit-learn.org/stable/auto_examples/model_selection/plot_grid_search_digits.html)) for your specific dataset, since they can vary between different datasets. Also it is recommendable to plot the 1D power spectrum to know how big or small the overlap between classes is.

![微信截图_20200326155135](https://user-images.githubusercontent.com/42901638/77622735-c5e3fb80-6f79-11ea-93c3-7f3c2eaa59c1.png)
thanks, it seems like my data's overlap is too small. It's hard to make data from 
video....

**Comment by RicardDurall** [comment]
It seems that for your case the difference in the spectrum is too small. You could try to increase the difference by using the inner part of the faces. Usually there, the content of the frequencies differ the most.

**Comment by MARD1NO** [comment]
> It seems that for your case the difference in the spectrum is too small. You could try to increase the difference by using the inner part of the faces. Usually there, the content of the frequencies differ the most.

thanks!I will try to add face recognize in making datasets.thanks for your reply!!!

**Comment by RicardDurall** [comment]
You are welcome! Please close the issue if you consider that is solved :)
