### ISSUE TITLE
Would you please release the pretrained model and show us how to run inference ?

### ISSUE THREAD

**Issue by CoinCheung** [cc-hpc-itwm/DeepFakeDetection#13]
Hi, 

Thanks for the great work, would you please upload your trained model and publish a few lines about how to run inference with the trained model ?

**Comment by RicardDurall** [comment]
Hi,
given that we use very simple classifiers (logistic regression and SVM), we do not provide the weights. You can reproduce results (and run inference) on the fly,  just by running the notebooks.

**Comment by CoinCheung** [comment]
Thanks for telling me this !!!
