### ISSUE TITLE
How many frames to use when input is a video?

### ISSUE THREAD

**Issue by arc144** [cc-hpc-itwm/DeepFakeDetection#2]
> Results based on videos. (We apply a simple majority vote over the single frame classifications).

So you used a single SVM to predict multiple frames and them used the mode (majority vote) as prediction? How many frames did you use? All of them?
Thanks

**Comment by RicardDurall** [comment]
Hello,
that's correct, we use a single SVM, and then we check the "majority vote". For this method, we take 20 frames per video.
