### ISSUE TITLE
What is “real data” in CelebA?

### ISSUE THREAD

**Issue by AkieWeng** [cc-hpc-itwm/DeepFakeDetection#21]
Hi! 
I tried to run CelebA.ipynb, but found that the “real data” in it did not seem to be given. Would you please tell me which dataset is used? Thank you!

**Comment by Allenem** [comment]
Hi, bro! I think all of images in the dataset CelebA are real data. So, what's the fake data? The images from other datasets? I noticed you closed this issue. Have you solved this problems? Can you tell me what data you or author used as real & fake data? Thanks a lot! 😄

**Comment by AkieWeng** [comment]
Hello! I noticed 'dataset_celebA/' was mentioned in [the code](https://github.com/cc-hpc-itwm/DeepFakeDetection/blob/master/Experiments_CelebA/CelebA.ipynb) as fake data, and I found that [this file](https://github.com/cc-hpc-itwm/DeepFakeDetection/blob/aaff429e0a90c09176dbcb7a754bbfc34b938741/Experiments_CelebA/dataset_celebA.7z) contains images that look like generated images.  
Therefore, I used CelebA as the real data and dataset_celebA.7z as the fake one.
