### ISSUE TITLE
Bug in radialProfile.py

### ISSUE THREAD

**Issue by SSAW14** [cc-hpc-itwm/DeepFakeDetection#3]
In line 18 of radialProfile.py,

it should be 
    center = np.array([(x.max()-x.min())/2.0, (y.max()-y.min())/2.0])
instead of 
    center = np.array([(x.max()-x.min())/2.0, (x.max()-x.min())/2.0]).

In current experiments, N*N images are applied, therefore, it performs okay.

**Comment by keuperj** [comment]
@RicardDurall : this kind of explains why non square face detection did not work so well :-)

**Comment by RicardDurall** [comment]
Thank you @SSAW14! The bug should be fixed
