### ISSUE TITLE
Update the code please

### ISSUE THREAD

**Issue by YLaCoon** [cc-hpc-itwm/DeepFakeDetection#6]
I am trying the reproduce your results but it's impossible. You just load a bunch of precomputed features. Please update your code and provide clear instructions on how the features were computed. 

For example:

```
# load feature file
pkl_file = open('train_3200.pkl', 'rb')
data = pickle.load(pkl_file)
pkl_file.close()
X = data["data"]
y = data["label"]
```

Were is the code to generate these pkl files? Why not use a simple csv file instead of folderNames.npy? Why do you copy `radialProfile.py` to every folder? Please also add a demo with a pretrained model that either takes a image or a video as input. How can anybody use this project otherwise?

**Comment by YLaCoon** [comment]
How is the train/val/test split generated?

**Comment by RicardDurall** [comment]
Hey,
in order to compute the features you could have used the code in the folder Experiments_Faces-HQ, where there is an example for Faces-HQ ( Faces-HQ.ipynb ). Anyway, we just added the preprocessing for the folder DeepFakeDetection so you should be able to run the whole experiment.
