### ISSUE TITLE
Wrong figure or wrong results

### ISSUE THREAD

**Issue by YLaCoon** [cc-hpc-itwm/DeepFakeDetection#8]
In TABLE VII of the paper it says 2000 samples. However, you are clearly loading and training with [3200 samples](https://github.com/cc-hpc-itwm/DeepFakeDetection/blob/master/Experiments_DeepFakeDetection/FaceForensic.ipynb). Either the figure or your results are wrong.

**Comment by RicardDurall** [comment]
In TABLE VII of the paper it says 2000, **1000, 200 and 20** samples. Here we provide an example with 3200 samples. I dont see the problem. You can just take 2000 and verify the results.

**Comment by YLaCoon** [comment]
Which 2000 samples can I take? `[:2000]` `[-2000:]`. To  make it clear: The score from the paper with 2000 samples is exactly the same score that I get if I run your code with 3200 samples. That is just coincidence. Is that correct?
